# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: app
# spec:
#   template:
#     metadata:
#       name: app
#     spec:
#       containers:
#       - name: app
#         image: dorin-web-app-app
#         imagePullPolicy: Never
#       restartPolicy: Never

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app
        image: dorin-web-app-app
        ports:
        - containerPort: 3000